In [2]:
import numpy as np

In [4]:
my_list = [1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
myarr = np.array(my_list)


In [7]:
type(myarr)

numpy.ndarray

In [8]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [9]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [15]:
np.zeros

<function numpy.zeros>

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [19]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [23]:
np.linspace(0, 10, 12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [24]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.random.rand(10)

array([0.49518133, 0.87571183, 0.95280959, 0.41072047, 0.47522466,
       0.05988452, 0.56374389, 0.39897268, 0.29775439, 0.21262958])

In [27]:
np.random.rand(10)

array([0.58943653, 0.74812673, 0.51692434, 0.26489289, 0.51491663,
       0.29192938, 0.48836351, 0.07873123, 0.70553858, 0.82861035])

In [28]:
np.random.rand(1)

array([0.17649037])

In [29]:
np.random.rand(1)

array([0.18545504])

In [30]:
np.random.rand(1)

array([0.94027232])

In [31]:
np.random.rand(1,5)

array([[0.05574721, 0.06263741, 0.53244694, 0.0297578 , 0.75895762]])

In [32]:
np.random.rand(5,6)

array([[0.60952567, 0.49719361, 0.43652116, 0.0186964 , 0.68168266,
        0.70454186],
       [0.82146137, 0.3673885 , 0.67389222, 0.86682832, 0.36273213,
        0.4575418 ],
       [0.65596371, 0.39396725, 0.10298565, 0.04163867, 0.91572236,
        0.94547418],
       [0.96604953, 0.96215349, 0.05060524, 0.14869858, 0.40355396,
        0.34940589],
       [0.16716292, 0.55765754, 0.40843268, 0.39664541, 0.72675566,
        0.39295856]])

In [33]:
np.random.randn(5,2)

array([[-0.28615379, -0.83053254],
       [-0.9610611 , -0.67563126],
       [ 0.18796843,  0.30759296],
       [-0.25482025,  0.49819995],
       [ 1.04275604, -1.28453115]])

In [34]:
np.random.randint(5)

3

In [35]:
np.random.rand(1,10)

array([[0.89830507, 0.35395976, 0.56184586, 0.10107244, 0.59303364,
        0.51141162, 0.07641928, 0.18828281, 0.56092499, 0.1878027 ]])

In [36]:
np.random.randint(1,10)

2

In [37]:
np.random.randint(1,100)

56

In [40]:
np.random.seed(40)
np.random.rand(4)

array([0.40768703, 0.05536604, 0.78853488, 0.28730518])

In [42]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [43]:
arr = np.arange(0, 25)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
ranarr = np.random.randint(0, 101, 10)

In [52]:
ranarr.reshape(2,5)

array([[ 9, 77, 40,  4, 63],
       [40, 60, 92, 64,  5]])

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
arr.shape

(25,)